### PR TITLE
Fix for Sketch 72

### LINKED ISSUE #13: Issue with MSApplicationMetadata
Hi Mathieu!

Looks like Sketch 72 the MSApplicationMetadata class has been replaced by BCSketchInfo.
I see sketch-module-google-analytics is still using MSApplicationMetadata (and having some issues with it :) ).

Is there any plan to update the analytics module?

Thanks!

### PR DESCRIPTION
**Pull request by bomberstudios**
Fixes #13

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -8,11 +8,12 @@ if (!uuid) {
   NSUserDefaults.standardUserDefaults().setObject_forKey(uuid, kUUIDKey)
 }
 
-var variant = MSApplicationMetadata.metadata().variant;
+var sketchVersion = Settings.version.sketch
+var variant = sketchVersion >= 72 ? BCSketchInfo.shared().metadata().variant : MSApplicationMetadata.metadata().variant
```
Comment (mathieudutour) [inline index.js:12]: I forgot about that, maybe it'd be an interesting info to surface in `sketch/Settings`

**Review by mathieudutour — APPROVED** [review]
Thanks for the PR!

File: index.js (hunk 1 above)
Comment (bomberstudios) [reply index.js:12]: Definitely, we’ll need to think about that.
